[package]
edition = "2021"
name = "peanut"
version = "0.1.0"
[dependencies]
bitmaps = "*"
clap = { version = "4.0.23", features = ["derive"] }
num-traits = "0.2.15"
paste = "1.0.9"
thiserror = "1.0.37"

