[package]
edition = "2021"
name = "peanut"
version = "0.1.0"
[dependencies]
bitflags = "1.3.2"
bitmaps = "*"
clap = { version = "4.0.23", features = ["derive"] }
paste = "1.0.9"
thiserror = "1.0.37"

